/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NutritionIndexRouteImport } from './routes/nutrition/index'
import { Route as NutritionHistoryRouteImport } from './routes/nutrition/history'
import { Route as NutritionTemplateEditorRouteImport } from './routes/nutrition/template-editor'
import { Route as WorkoutIndexRouteImport } from './routes/workout/index'
import { Route as WorkoutActiveRouteImport } from './routes/workout/active'
import { Route as WorkoutHistoryRouteImport } from './routes/workout/history'
import { Route as WorkoutTemplatesRouteImport } from './routes/workout/templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/nutrition/',
  path: '/nutrition/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionHistoryRoute = NutritionHistoryRouteImport.update({
  id: '/nutrition/history',
  path: '/nutrition/history',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionTemplateEditorRoute = NutritionTemplateEditorRouteImport.update({
  id: '/nutrition/template-editor',
  path: '/nutrition/template-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/workout/',
  path: '/workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutActiveRoute = WorkoutActiveRouteImport.update({
  id: '/workout/active',
  path: '/workout/active',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutHistoryRoute = WorkoutHistoryRouteImport.update({
  id: '/workout/history',
  path: '/workout/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutTemplatesRoute = WorkoutTemplatesRouteImport.update({
  id: '/workout/templates',
  path: '/workout/templates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/nutrition/history': typeof NutritionHistoryRoute
  '/nutrition/template-editor': typeof NutritionTemplateEditorRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/history': typeof WorkoutHistoryRoute
  '/workout/templates': typeof WorkoutTemplatesRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/nutrition/history': typeof NutritionHistoryRoute
  '/nutrition/template-editor': typeof NutritionTemplateEditorRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/history': typeof WorkoutHistoryRoute
  '/workout/templates': typeof WorkoutTemplatesRoute
  '/nutrition': typeof NutritionIndexRoute
  '/workout': typeof WorkoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/nutrition/history': typeof NutritionHistoryRoute
  '/nutrition/template-editor': typeof NutritionTemplateEditorRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/history': typeof WorkoutHistoryRoute
  '/workout/templates': typeof WorkoutTemplatesRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/progress'
    | '/settings'
    | '/nutrition/history'
    | '/nutrition/template-editor'
    | '/workout/active'
    | '/workout/history'
    | '/workout/templates'
    | '/nutrition/'
    | '/workout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/progress'
    | '/settings'
    | '/nutrition/history'
    | '/nutrition/template-editor'
    | '/workout/active'
    | '/workout/history'
    | '/workout/templates'
    | '/nutrition'
    | '/workout'
  id:
    | '__root__'
    | '/'
    | '/progress'
    | '/settings'
    | '/nutrition/history'
    | '/nutrition/template-editor'
    | '/workout/active'
    | '/workout/history'
    | '/workout/templates'
    | '/nutrition/'
    | '/workout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  NutritionHistoryRoute: typeof NutritionHistoryRoute
  NutritionTemplateEditorRoute: typeof NutritionTemplateEditorRoute
  WorkoutActiveRoute: typeof WorkoutActiveRoute
  WorkoutHistoryRoute: typeof WorkoutHistoryRoute
  WorkoutTemplatesRoute: typeof WorkoutTemplatesRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/nutrition'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/history': {
      id: '/nutrition/history'
      path: '/nutrition/history'
      fullPath: '/nutrition/history'
      preLoaderRoute: typeof NutritionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/template-editor': {
      id: '/nutrition/template-editor'
      path: '/nutrition/template-editor'
      fullPath: '/nutrition/template-editor'
      preLoaderRoute: typeof NutritionTemplateEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/active': {
      id: '/workout/active'
      path: '/workout/active'
      fullPath: '/workout/active'
      preLoaderRoute: typeof WorkoutActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/history': {
      id: '/workout/history'
      path: '/workout/history'
      fullPath: '/workout/history'
      preLoaderRoute: typeof WorkoutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/templates': {
      id: '/workout/templates'
      path: '/workout/templates'
      fullPath: '/workout/templates'
      preLoaderRoute: typeof WorkoutTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  NutritionHistoryRoute: NutritionHistoryRoute,
  NutritionTemplateEditorRoute: NutritionTemplateEditorRoute,
  WorkoutActiveRoute: WorkoutActiveRoute,
  WorkoutHistoryRoute: WorkoutHistoryRoute,
  WorkoutTemplatesRoute: WorkoutTemplatesRoute,
  NutritionIndexRoute: NutritionIndexRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
